### ISSUE TITLE
4주차 4-2, 4-3 퀴즈에 답을 적을 수 없는 문제 관련 문의입니다

### ISSUE THREAD

**Issue by hijihyun** [advanced-webapps-class/start-fe-2021#1]
안녕하세요? 고급웹개발론 수강중인 김지현이라고 합니다. 다름이 아니고 링크로 첨부한 사진과 같이 4주차 4-2, 4-3 퀴즈에 답을 적는 칸이 없는 문제들이 있어서요. 질문만 있습니다. 어떻게 해야 하는지 알려주시면 감사하겠습니다.

https://drive.google.com/file/d/1e5hPGSALMYwk8G4PT7ZQPxhqzCkYm0xo/view?usp=sharing

**Comment by niceaji** [comment]
@hijihyun 아고 그러네요. 수정했습니다. 알려주셔서 고맙습니다

**Comment by hijihyun** [comment]
주말에는 확인을 안 하실 줄 알고 미리 문의를 해 두었는데... 죄송합니다... 앞으로는 문의할 게 있다면 평일에 여쭤보겠습니다... 감사합니다. 좋은하루되세요

**Comment by niceaji** [comment]
@hijihyun 아녜요. 괜찮습니다 ^^
