### ISSUE TITLE
과제 제출에 대하여 질문있습니다. 

### ISSUE THREAD

**Issue by hyunmuam** [advanced-webapps-class/start-fe-2021#2]
저희 과제 제출 조건이 다음과 같습니다.
1. private 레파지토리 생성 (1boon-tab)
2. 의미에 맞는 commit 메세지 작성
3. https://github.io/{본인의ID}/1boon-tab
4. niceaji collaborator로 레파지토리 초대

저희가 레포를 private로 만들고 page옵션으로 들어가게되면 되면 다음과 같이 경고문이 뜹니다.
GitHub Pages is designed to host your personal, organization, or project pages from a GitHub repository.

저희가 깃허브 유료 라이센스가 없어서 나오는 경고창인것 같은데 그냥 깃 페이지주소가 아닌 레포 주소로 넘겨주면 될까요?

**Comment by niceaji** [comment]
제가 페이지주소로 남겨달라고 했었나요?
과제제출 폼에서 https://github.io/{본인의ID}/1boon-tab  레파지토리 주소로  남겨주시면 됩니다.
( private레포에서  깃헙페이지 기능은 유료입니다)
@tjvm0877

**Comment by hyunmuam** [comment]
아 https://github.com/{깃아이디}/1boon-tab가 아니라 github.io. 로 제출하라고 하시길레 깃 페이지 주소를 보내달라고 착각한것 같습니다.

**Comment by niceaji** [comment]
@tjvm0877  그러네요. .com으로 수정했습니다.

**Comment by hyunmuam** [comment]
@niceaji 그리고 제주대학교 이메일이 있으면 https://education.github.com을 통하여 학생인증을하여 다른 IDE처럼 프로 라이센스로 올릴 수 있지만 저도 그렇고 학생인증을 하지 않은 학생들도 있을 것같아서 여쭤보았습니다. 답변 갑사합니다!
