### ISSUE TITLE
커밋 기한에 대한 문의 드립니다.

### ISSUE THREAD

**Issue by hoonisone** [advanced-webapps-class/start-fe-2021#4]
구글 설문지는 작성해서 제출했는데 이후 29일 0시 까지 추가 수정이 가능한가요? 사실 이미 했어요..ㅠ

**Comment by niceaji** [comment]
감점요인이 될것 같습니다.  @hoonisone

**Comment by hoonisone** [comment]
혹시 구글 폼 제출 전에 커밋 내용으로 채점해주실 수 있나요. 제출 후  바로 어노테이션 추가와 쓰이지 않는 변수 제거만 제거한 거라서 구현 결과는 동일합니다.
